
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import 'Test.sol';

// This is class that describes you smart contract.
contract test2 {

    function callAddress() public {
        Test tes;
        tes.addressReturn();
    }
    
}
