
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
interface GamingObjectInterface {
   function takeAHit(uint attackValue) external;
   
   /*  
   destroyUnitIfBaseIsDead is declared in Interface to be avaliable from BaseStation contract 
   As that contract BaseStation doesnt import WarUnit (the original declaration of destroyUnitIfBaseIsDead). 
   */

   function destroyUnitIfBaseIsDead() external;

   //function addUnit(GamingObjectInterface unitAddress) external;
   //function destroyUnit() external;

}