
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract Token {
    
    struct NinjaToken {
        string name;
        uint power;
        string clan;
        string rank;
        uint price;
    }

    NinjaToken[] tokensArray;
    mapping (uint => uint) tokenToOwner;

    constructor() public {
    
        require(tvm.pubkey() != 0, 101);
        
        require(msg.pubkey() == tvm.pubkey(), 102);
        
        tvm.accept();
    }

    function createToken(string name, uint power, string clan, string rank) public {
        tvm.accept();
        for (uint256 index = 0; index < tokensArray.length; index++) {
            require(name != tokensArray[index].name);
        }
        tokensArray.push(NinjaToken(name, power, clan, rank, 0));
        uint keyAsLastNumber = tokensArray.length - 1;
        tokenToOwner[keyAsLastNumber] = msg.pubkey();
    }

    function changePrice(uint tokenId, uint price) public {
        require(msg.pubkey() == tokenToOwner[tokenId], 101);
        tvm.accept();
        tokensArray[tokenId].price = price;
        
    }

    function getTokenOwner(uint tokenId) public view returns (uint){
        // tvm.accept();
        return tokenToOwner[tokenId];
    }

    function getTokenInfo(uint tokenId) public view returns (string tokenName, uint tokenPower, string tokenClan, string tokenRank, uint tokenPrice){
        // tvm.accept();
        tokenName = tokensArray[tokenId].name;
        tokenPower = tokensArray[tokenId].power;
        tokenClan = tokensArray[tokenId].clan;
        tokenRank = tokensArray[tokenId].rank;
        tokenPrice = tokensArray[tokenId].price;
    }
}