
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


contract Line {
    
	string[] public line;

	constructor() public {
		
		require(tvm.pubkey() != 0, 101);
		
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
	}

	modifier checkOwnerAndAccept {
		
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}

	function add(string value) public checkOwnerAndAccept {
		line.push(value);
	}

	function callFirst() public checkOwnerAndAccept {
		for (uint256 index = 0; index < line.length - 1; index++) {
			line[index] = line[index + 1];
		}
		line.pop();
	}
}